systemLog:
  destination: file
  path: /dev/null
  quiet: true
  verbosity: 0
  component:
    accessControl:
      verbosity: -1
    command:
      verbosity: -1
    control:
      verbosity: -1
    geo:
      verbosity: -1
    index:
      verbosity: -1
    network:
      verbosity: -1
    query:
      verbosity: -1
    replication:
      verbosity: -1
    sharding:
      verbosity: -1
    storage:
      verbosity: -1
    write:
      verbosity: -1
net:
  bindIpAll: true
storage:
  dbPath: /data/db
